"""empty message

Revision ID: 1fa71539185e
Revises: 3f2b514bf84f
Create Date: 2015-03-02 04:15:25.470215

"""

# revision identifiers, used by Alembic.
revision = '1fa71539185e'
down_revision = '3f2b514bf84f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_column('users', 'confirmed_at')
    op.drop_column('users', 'active')
    ### end Alembic commands ###
