"""empty message

Revision ID: 446b94f8e667
Revises: 1fa71539185e
Create Date: 2015-03-08 08:38:19.696559

"""

# revision identifiers, used by Alembic.
revision = '446b94f8e667'
down_revision = '1fa71539185e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('users', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'name')
    ### end Alembic commands ###
