"""empty message

Revision ID: 4ea728c0b56
Revises: None
Create Date: 2015-02-25 02:05:48.704241

"""

# revision identifiers, used by Alembic.
revision = '4ea728c0b56'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
