"""empty message

Revision ID: 57a16e98d7d8
Revises: 446b94f8e667
Create Date: 2015-03-08 12:10:03.871987

"""

# revision identifiers, used by Alembic.
revision = '57a16e98d7d8'
down_revision = '446b94f8e667'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'image')
    ### end Alembic commands ###
