"""empty message

Revision ID: 48c207a8d590
Revises: 939abbc292e
Create Date: 2015-03-06 14:11:07.745539

"""

# revision identifiers, used by Alembic.
revision = '48c207a8d590'
down_revision = '939abbc292e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_path', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_path')
    ### end Alembic commands ###
