"""empty message

Revision ID: 939abbc292e
Revises: 399106d8a6ad
Create Date: 2015-03-06 13:13:35.821046

"""

# revision identifiers, used by Alembic.
revision = '939abbc292e'
down_revision = '399106d8a6ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('company', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'company')
    ### end Alembic commands ###
